/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: vision.i

package vision

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef long long swig_type_1;
typedef long long swig_type_2;
typedef long long swig_type_3;
typedef long long swig_type_4;
typedef _gostring_ swig_type_5;
typedef _gostring_ swig_type_6;
typedef _gostring_ swig_type_7;
typedef _gostring_ swig_type_8;
typedef _gostring_ swig_type_9;
typedef _gostring_ swig_type_10;
extern void _wrap_Swig_free_vision_b51e859bb7108b12(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_vision_b51e859bb7108b12(swig_intgo arg1);
extern uintptr_t _wrap_new_ByteVector__SWIG_0_vision_b51e859bb7108b12(void);
extern uintptr_t _wrap_new_ByteVector__SWIG_1_vision_b51e859bb7108b12(swig_type_1 arg1);
extern uintptr_t _wrap_new_ByteVector__SWIG_2_vision_b51e859bb7108b12(uintptr_t arg1);
extern swig_type_2 _wrap_ByteVector_size_vision_b51e859bb7108b12(uintptr_t arg1);
extern swig_type_3 _wrap_ByteVector_capacity_vision_b51e859bb7108b12(uintptr_t arg1);
extern void _wrap_ByteVector_reserve_vision_b51e859bb7108b12(uintptr_t arg1, swig_type_4 arg2);
extern _Bool _wrap_ByteVector_isEmpty_vision_b51e859bb7108b12(uintptr_t arg1);
extern void _wrap_ByteVector_clear_vision_b51e859bb7108b12(uintptr_t arg1);
extern void _wrap_ByteVector_add_vision_b51e859bb7108b12(uintptr_t arg1, char arg2);
extern char _wrap_ByteVector_get_vision_b51e859bb7108b12(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_ByteVector_set_vision_b51e859bb7108b12(uintptr_t arg1, swig_intgo arg2, char arg3);
extern void _wrap_delete_ByteVector_vision_b51e859bb7108b12(uintptr_t arg1);
extern swig_type_5 _wrap_DogsVsCats_DOG_get_vision_b51e859bb7108b12(uintptr_t arg1);
extern swig_type_6 _wrap_DogsVsCats_CAT_get_vision_b51e859bb7108b12(uintptr_t arg1);
extern void _wrap_DogsVsCats_load_vision_b51e859bb7108b12(uintptr_t arg1, swig_type_7 arg2);
extern swig_type_8 _wrap_DogsVsCats_predict_vision_b51e859bb7108b12(uintptr_t arg1, uintptr_t arg2);
extern swig_type_9 _wrap_DogsVsCats_predictByUrl_vision_b51e859bb7108b12(uintptr_t arg1, swig_type_10 arg2);
extern uintptr_t _wrap_new_DogsVsCats_vision_b51e859bb7108b12(void);
extern void _wrap_delete_DogsVsCats_vision_b51e859bb7108b12(uintptr_t arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex


type swig_gostring struct { p uintptr; n int }
func swigCopyString(s string) string {
  p := *(*swig_gostring)(unsafe.Pointer(&s))
  r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
  Swig_free(p.p)
  return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_vision_b51e859bb7108b12(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_vision_b51e859bb7108b12(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type SwigcptrByteVector uintptr

func (p SwigcptrByteVector) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrByteVector) SwigIsByteVector() {
}

func NewByteVector__SWIG_0() (_swig_ret ByteVector) {
	var swig_r ByteVector
	swig_r = (ByteVector)(SwigcptrByteVector(C._wrap_new_ByteVector__SWIG_0_vision_b51e859bb7108b12()))
	return swig_r
}

func NewByteVector__SWIG_1(arg1 int64) (_swig_ret ByteVector) {
	var swig_r ByteVector
	_swig_i_0 := arg1
	swig_r = (ByteVector)(SwigcptrByteVector(C._wrap_new_ByteVector__SWIG_1_vision_b51e859bb7108b12(C.swig_type_1(_swig_i_0))))
	return swig_r
}

func NewByteVector__SWIG_2(arg1 ByteVector) (_swig_ret ByteVector) {
	var swig_r ByteVector
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (ByteVector)(SwigcptrByteVector(C._wrap_new_ByteVector__SWIG_2_vision_b51e859bb7108b12(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewByteVector(a ...interface{}) ByteVector {
	argc := len(a)
	if argc == 0 {
		return NewByteVector__SWIG_0()
	}
	if argc == 1 {
		if _, ok := a[0].(int64); !ok {
			goto check_2
		}
		return NewByteVector__SWIG_1(a[0].(int64))
	}
check_2:
	if argc == 1 {
		return NewByteVector__SWIG_2(a[0].(ByteVector))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrByteVector) Size() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_ByteVector_size_vision_b51e859bb7108b12(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrByteVector) Capacity() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_ByteVector_capacity_vision_b51e859bb7108b12(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrByteVector) Reserve(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_ByteVector_reserve_vision_b51e859bb7108b12(C.uintptr_t(_swig_i_0), C.swig_type_4(_swig_i_1))
}

func (arg1 SwigcptrByteVector) IsEmpty() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_ByteVector_isEmpty_vision_b51e859bb7108b12(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrByteVector) Clear() {
	_swig_i_0 := arg1
	C._wrap_ByteVector_clear_vision_b51e859bb7108b12(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrByteVector) Add(arg2 byte) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_ByteVector_add_vision_b51e859bb7108b12(C.uintptr_t(_swig_i_0), C.char(_swig_i_1))
}

func (arg1 SwigcptrByteVector) Get(arg2 int) (_swig_ret byte) {
	var swig_r byte
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (byte)(C._wrap_ByteVector_get_vision_b51e859bb7108b12(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrByteVector) Set(arg2 int, arg3 byte) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_ByteVector_set_vision_b51e859bb7108b12(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.char(_swig_i_2))
}

func DeleteByteVector(arg1 ByteVector) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_ByteVector_vision_b51e859bb7108b12(C.uintptr_t(_swig_i_0))
}

type ByteVector interface {
	Swigcptr() uintptr
	SwigIsByteVector()
	Size() (_swig_ret int64)
	Capacity() (_swig_ret int64)
	Reserve(arg2 int64)
	IsEmpty() (_swig_ret bool)
	Clear()
	Add(arg2 byte)
	Get(arg2 int) (_swig_ret byte)
	Set(arg2 int, arg3 byte)
}

type SwigcptrDogsVsCats uintptr

func (p SwigcptrDogsVsCats) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrDogsVsCats) SwigIsDogsVsCats() {
}

func (arg1 SwigcptrDogsVsCats) GetDOG() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_DogsVsCats_DOG_get_vision_b51e859bb7108b12(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrDogsVsCats) GetCAT() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_DogsVsCats_CAT_get_vision_b51e859bb7108b12(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrDogsVsCats) Load(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_DogsVsCats_load_vision_b51e859bb7108b12(C.uintptr_t(_swig_i_0), *(*C.swig_type_7)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrDogsVsCats) Predict(arg2 ByteVector) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r_p := C._wrap_DogsVsCats_predict_vision_b51e859bb7108b12(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrDogsVsCats) PredictByUrl(arg2 string) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r_p := C._wrap_DogsVsCats_predictByUrl_vision_b51e859bb7108b12(C.uintptr_t(_swig_i_0), *(*C.swig_type_10)(unsafe.Pointer(&_swig_i_1)))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func NewDogsVsCats() (_swig_ret DogsVsCats) {
	var swig_r DogsVsCats
	swig_r = (DogsVsCats)(SwigcptrDogsVsCats(C._wrap_new_DogsVsCats_vision_b51e859bb7108b12()))
	return swig_r
}

func DeleteDogsVsCats(arg1 DogsVsCats) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_DogsVsCats_vision_b51e859bb7108b12(C.uintptr_t(_swig_i_0))
}

type DogsVsCats interface {
	Swigcptr() uintptr
	SwigIsDogsVsCats()
	GetDOG() (_swig_ret string)
	GetCAT() (_swig_ret string)
	Load(arg2 string)
	Predict(arg2 ByteVector) (_swig_ret string)
	PredictByUrl(arg2 string) (_swig_ret string)
}


